travis:
  secure:
    BINSTAR_TOKEN: CMurPuBlRmZfYYrObeldupOr2I0LQsAu5aI+PkueR7WTIWbcFx6qKY9yQEYEhsl8om30DsHOcrs6uy5qcII12NrMiUzNoEGE79tkesBrn7hPkHIxlb0B/z9N/zsgkdCHNUMrP1pQe9bjTuADMjVJmWBARM2yhbWEE49lGcURJKT9lyW9y5SPS3V+M6F7hvItdBe/xjDlEgKq2HI3csJ/ca9gR43Tr6QemDLMGu374/JxYlpdrqpZuW0YW91LZ5t1+zbnVfpkfyBAM5sL5L37ylUL5QL9Fr67eXoOOzRMQwIRyIJq4aaOZLW2bTPZnLKL4kOKGTbH/1Pmo3DFaw7hrDuB/8L+HFZ92sbSIauU0qNhg4Hq6b07Ry+wg7XY6rw9XPkpz+ftDZ7hzII/NqCm5V1G50XjsivEQawKEuWa7ImYcC6QgJXkGQvBHlSb6xUfsLuYbI+ATeGEQ3huxCx9gQ9TpC0ODMwV8OSlnyZLkdhlv8Xrz91kAXGVXQPTq82CdsvgcEUuKNWJ62FkXi/Ym6Q+Q95GfZY4chnUwemLaeIr3GjqM7u9suT69SCUlE2G1rhunwOcXooABTmQEKB55qIaZb11i6KDCA7eXMJ3BT8HZxiE+DnDXppRF1b66RgZLP1RwXhgqtu16xTQSqxjKH59HVaT5URXvQh44nvN+s4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
